language: node_js
sudo: required
cache: yarn
env:
  global:
  - ENCRYPTION_LABEL: "b601314e09dc"
  - COMMIT_AUTHOR_EMAIL: "dgutride@gmail.com"
  - COMMIT_AUTHOR_USERNAME: "dgutride"
  - TRIGGER_REPO_SLUG: "pfbreakaway/breakaway-patternfly-react"
  - TRIGGER_REPO_BRANCH: "master"
notifications:
  email: false
before_install:
- .travis/before_install.sh
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
- export PATH=$HOME/.yarn/bin:$PATH
- yarn install
script:
- yarn build
after_success:
- .travis/after_success.sh
git:
  depth: 1
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
